# Generated by Django 2.0.2 on 2022-07-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_auto_20220715_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ordencompra1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.IntegerField(blank=True, null=True, verbose_name='Numero Pedido')),
                ('precio_orden', models.IntegerField(blank=True, null=True, verbose_name='Precio Orden')),
                ('cantidad_orden', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Orden')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('estado_pedido', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=100, null=True, verbose_name='Estado Pedido')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
            options={
                'verbose_name': 'Ordencompra1',
                'verbose_name_plural': 'Ordenescompra1',
                'ordering': ['numero_pedido'],
            },
        ),
    ]
