# Generated by Django 2.0.2 on 2022-07-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_auto_20220715_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='P1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(blank=True, max_length=100, verbose_name='Nombre Proveedor')),
                ('rut_proveedor', models.CharField(blank=True, max_length=13, verbose_name='Rut Proveedor')),
                ('correo_proveedor', models.CharField(blank=True, max_length=50, verbose_name='Correo Proveedor')),
                ('telefono_proveedor', models.CharField(blank=True, max_length=15, verbose_name='Telefono Proveedor')),
                ('direccion_proveedor', models.CharField(blank=True, max_length=60, null=True, verbose_name='Direccion Proveedor')),
                ('estado_proveedor', models.CharField(choices=[('Activo', 'Activar'), ('Inactivo', 'Desactivar')], default='Activo', max_length=100, null=True, verbose_name='Estado Proveedor')),
                ('dato_producto', models.ManyToManyField(related_name='get_productos', to='productos.Producto', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'P1',
                'verbose_name_plural': 'P1',
                'ordering': ['nombre_proveedor'],
            },
        ),
    ]
