# Generated by Django 2.0.2 on 2022-06-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Categoria')),
                ('state', models.CharField(blank=True, default='Activo', max_length=50, null=True, verbose_name='Estado Categoria')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=100, verbose_name='Nombre Producto')),
                ('sku_producto', models.CharField(blank=True, max_length=12, verbose_name='SKU Producto')),
                ('codigo_barras_producto', models.CharField(blank=True, max_length=12, verbose_name='Codigo Barras Producto')),
                ('precio_producto', models.CharField(blank=True, max_length=9, verbose_name='Precio Producto')),
                ('costo_producto', models.CharField(blank=True, max_length=9, verbose_name='Precio Producto')),
                ('stock_producto', models.IntegerField(blank=True, null=True, verbose_name='Stock Producto')),
                ('stock_promedio', models.IntegerField(blank=True, null=True, verbose_name='Stock Promedio Producto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, default='Activo', max_length=50, null=True, verbose_name='Estado Prodcuto')),
            ],
        ),
    ]
