# Generated by Django 2.0.2 on 2022-07-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('p1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='V1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vendedor', models.CharField(blank=True, max_length=100, verbose_name='Nombre Vendedor')),
                ('rut_vendedor', models.CharField(blank=True, max_length=13, verbose_name='Rut Vendedor')),
                ('telefono_vendedor', models.CharField(blank=True, max_length=15, verbose_name='Telefono Vendedor')),
                ('correo_vendedor', models.CharField(blank=True, max_length=50, verbose_name='Correo Vendedor')),
                ('estado_vendedor', models.CharField(blank=True, default='Activo', max_length=20, null=True, verbose_name='Estado Vendedor')),
                ('dato_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p1.P1')),
            ],
            options={
                'verbose_name': 'V1',
                'verbose_name_plural': 'Vends',
                'ordering': ['nombre_vendedor'],
            },
        ),
    ]
